### ISSUE TITLE
I want to get  multi-dimentional rows with where filetr option using typeorm

### ISSUE THREAD

**Issue by worldseven** [worldseven/typeorm_express#1]
I am developing apis using express.js and typeorm.
There are some tables:albums, tracks, artist.
There have one to many relations.
I need to get the limited albums that one of those' tracks has the specific category.
I tried with this:
 const albums2 = await albumRepository.find(
       {
         relations: [
           "category",
           "publisher",
           "language",
           "tracks",
           "tracks.artists",
           "tracks.category",
           "tracks.key",
         ],
         order: { created_at: "DESC" },
       })
     const filterAlbums = albums2.filter((item) => {
       let isContain = false;
       item.tracks.map((track) => {
         if (track.category.id == category.id) {
           isContain = true;
         }
       })
       return isContain;
     })
     const count = filterAlbums.length;
     const finalAlbums = filterAlbums.slice(Number(skip), Number(skip) + Number(limit))
I tried above code,
It worked well but the time is too long.
I want to optimize this api.

**Comment by crazynavi** [comment]
I got what you want.
Please try with following code.
    const entityManager = getManager();
    const res = await entityManager.query(`SELECT album_id FROM tracks WHERE tracks.category_id = ${category.id} AND tracks.deleted_at IS NULL GROUP BY tracks.album_id DESC LIMIT ${limit} OFFSET ${skip}`);
    const couter = await entityManager.query(`SELECT album_id FROM tracks WHERE tracks.category_id = ${category.id} AND tracks.deleted_at IS NULL GROUP BY tracks.album_id`);
    const album_ids = res.map((item: { album_id: any; }) => { return item.album_id });
    const testalbums = await albumRepository.find(
      {
        where: { id: In(album_ids) },
        relations: [
          "category",
          "publisher",
          "language",
          "tracks",
          "tracks.artists",
          "tracks.category",
          "tracks.key",
        ],
        order: { created_at: "DESC" },
      })
      I used both of typeorm and pure sql.
      I hope this is helpful to you.

**Comment by worldseven** [comment]
Thanks,
This works for me very good.
